### ISSUE TITLE
Could not build the project (multiple definitions errors)

### ISSUE THREAD

**Issue by ptal** [maximaximal/Paracooba#2]
Hello,

I tried to build the project but couldn't succeed due to some linking errors.
I attached the output of make.
Did I miss something?

Best
Pierre
[output.txt](https://github.com/maximaximal/Paracooba/files/5276775/output.txt)

**Comment by maximaximal** [comment]
Hello,

sorry for the very late answer, I must have missed a mail from GitHub about the notification. 

This is a known problem with some compilers and the March dependency and can fortunately be fixed by changing its Makefile. I already developed a fix during the modularization effort (see branch modularization) and backported it into the main branch. The compile works without errors (only with warnings from March) again on my machine without any other changes after cloning master. I tested with g++7 and g++10.

I hope this fixes your issue too!

Best,
Max
